// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sqdsHZwo7WyFtvHhyVlDyCI03d2It1E',
    appId: '1:653657708900:web:2c52b6fbcbe0d47f194271',
    messagingSenderId: '653657708900',
    projectId: 'counter-firebase-3246b',
    authDomain: 'counter-firebase-3246b.firebaseapp.com',
    databaseURL: 'https://counter-firebase-3246b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'counter-firebase-3246b.appspot.com',
    measurementId: 'G-T0HYP9977Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWk44NsWnmlhtLcM06Yfq249Tk4TnbVXU',
    appId: '1:653657708900:android:ad82bf7f2d566920194271',
    messagingSenderId: '653657708900',
    projectId: 'counter-firebase-3246b',
    databaseURL: 'https://counter-firebase-3246b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'counter-firebase-3246b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQrosUK-3J4nY0csieAd1g8a5owCPLDo',
    appId: '1:653657708900:ios:6a4f67b05b271515194271',
    messagingSenderId: '653657708900',
    projectId: 'counter-firebase-3246b',
    databaseURL: 'https://counter-firebase-3246b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'counter-firebase-3246b.appspot.com',
    iosClientId: '653657708900-05phramghl4dsgfitnbf4ked4ce2ln4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQrosUK-3J4nY0csieAd1g8a5owCPLDo',
    appId: '1:653657708900:ios:6a4f67b05b271515194271',
    messagingSenderId: '653657708900',
    projectId: 'counter-firebase-3246b',
    databaseURL: 'https://counter-firebase-3246b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'counter-firebase-3246b.appspot.com',
    iosClientId: '653657708900-05phramghl4dsgfitnbf4ked4ce2ln4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSample',
  );
}
