// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_7mPV1ErwSoqGyFv7qY__ifbhjo0gOA',
    appId: '1:610772511294:web:15949e6e0dbc8469f27f6f',
    messagingSenderId: '610772511294',
    projectId: 'game-sample-280a2',
    authDomain: 'game-sample-280a2.firebaseapp.com',
    storageBucket: 'game-sample-280a2.appspot.com',
    measurementId: 'G-5FVBEZFHXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfI1GRNkNbJGe8aZoWvMVGslSNHLMaV8',
    appId: '1:610772511294:android:9495a29e41df71d5f27f6f',
    messagingSenderId: '610772511294',
    projectId: 'game-sample-280a2',
    storageBucket: 'game-sample-280a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJnbc2BQ57DzUsWRiDkRdmtl1dxAomcXI',
    appId: '1:610772511294:ios:f7720c354ec77288f27f6f',
    messagingSenderId: '610772511294',
    projectId: 'game-sample-280a2',
    storageBucket: 'game-sample-280a2.appspot.com',
    iosClientId: '610772511294-mso3g7tt793s2onrd93731s65o0ng8vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJnbc2BQ57DzUsWRiDkRdmtl1dxAomcXI',
    appId: '1:610772511294:ios:f7720c354ec77288f27f6f',
    messagingSenderId: '610772511294',
    projectId: 'game-sample-280a2',
    storageBucket: 'game-sample-280a2.appspot.com',
    iosClientId: '610772511294-mso3g7tt793s2onrd93731s65o0ng8vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSample',
  );
}
